### ISSUE TITLE
No Plugin information in the backend

### ISSUE THREAD

**Issue by kludikovsky** [pixelink/typo3-simplepoll#11]
I don't get any plugin informaiton displayed in the backend.

Installed all according the description (at least I believe I did) but I do not get any options displayed to bring the plugin to the page.

**Comment by alexxB** [comment]
Sorry, I can not see a Problem. 

> I do not get any options displayed to bring the plugin to the page

I have no Idea what you mean by that

**Comment by kludikovsky** [comment]
Sorry for being so unspecific.

Extension installed
![_screen_shot_2018-01-03_095433](https://user-images.githubusercontent.com/6077916/34514428-b4191f3a-f06d-11e7-8a3e-3eb5dde46e7b.jpg)

Template included
![_screen_shot_2018-01-03_095240](https://user-images.githubusercontent.com/6077916/34514455-ccbdbc44-f06d-11e7-9666-a76d9a9f6b5d.jpg)

Default Storage PID set
![_screen_shot_2018-01-03_095330](https://user-images.githubusercontent.com/6077916/34514517-17bcab6a-f06e-11e7-8164-a34a4ed6b0a8.jpg)


No SimplePoll Element to insert available
![_screen_shot_2018-01-03_095056](https://user-images.githubusercontent.com/6077916/34514473-e3153fd0-f06d-11e7-8998-ba981a6bd2a5.jpg)


Please let me know if you need some more information.

Used T3 Version 7.6.18

PS:
There is no intereference with myquiypoll as this has been installed afterwards as I  has to solve an urgent issue.

**Comment by alexxB** [comment]
Simplepoll records are not allowed on standard pages. Changing the "Test Survey" page to a folder should solve that.

**Comment by kludikovsky** [comment]
OK, thx. Worked.
