### ISSUE TITLE
Migrate to TYPO3 9.x and PHP 7.2

### ISSUE THREAD

**Issue by nicozerr** [pixelink/typo3-simplepoll#12]
Hi.

TYPO3 9.x has been released. Will ext:simplepoll be migrated for this version ?

Thank you.

**Comment by alexxB** [comment]
Hi Nicolas,

yes there will be a migrated version for the upcoming 9 LTS. Not on release day but i guess not too far from it either.

Cheers

Alex

**Comment by alexxB** [comment]
a partly tested Version for 9.4 is in the master brach if you fancy to try.
Hope 9.5 does not bring more breaking changes we have to tackle
