### ISSUE TITLE
Add new slug field for url segments

### ISSUE THREAD

**Issue by nicozerr** [pixelink/typo3-simplepoll#14]
Hello.

Please add a new field 'url_segment' with type 'slug', for the new TYPO3 routing.

Thank you !

**Comment by alexxB** [comment]
As a start: I haven't used 9.3+ routing, nor have I ever done something with realurl so far.

Why would simplepoll need routing/slug information? Since it is using ajax calls there should never be any part of the URL changed by it.

**Comment by nicozerr** [comment]
Oh sorry. You're right.
I use to work with an additionnal extension that displays all my polls in a list view, so I have a single view for each poll from a sysfolder.
The slug must be added in this custom extension, not yours.
