### ISSUE TITLE
Issue with cookie storage when countLanguagesSeperately is set to false

### ISSUE THREAD

**Issue by Azazel1333** [pixelink/typo3-simplepoll#16]
Relevant Settings: 
[plugin.tx_simplepoll.settings.countLanguagesSeperately] = 0
[plugin.tx_simplepoll.settings.ipBlock] = 0
[plugin.tx_simplepoll.settings.cookieBlock] = 1

Issue: When a user votes on \<domain>/en they are allowed to submit a second vote on \<domain>/fr. 

What this means is that the settings.cookieBlock, without the IP restriction, doesn't account for multiple languages. 

Expected behavior: If a user votes on \<domain>/en they should no longer be allowed to vote on \<domain>/fr.

**Comment by alexxB** [comment]
I will have a look into this sometime. 
Thanks for reporting.

**Comment by alexxB** [comment]
Yep, cookies have not been stored in the root. 
Thanks a lot.

(v3.1.3 has it fixed)
