### ISSUE TITLE
TYPO3 v10 compatibility

### ISSUE THREAD

**Issue by AKaravas** [pixelink/typo3-simplepoll#18]
The title is self explanatory and not much information needed to describe it. :)

Are you considering creating a TYPO3 v10 version? I would love to use it on my TYPO3 v10 Projects

💯 🥇 👍

**Comment by briezler** [comment]
Hey, yes we will provide an update for v10. But actually i'm a little out of time. But there will be an update within the next weeks.

**Comment by janisint** [comment]
@briezler Are there any news?

**Comment by briezler** [comment]
We just released v 4.0.0 wich is TYPO3 10.4 compatible.
