### ISSUE TITLE
Multiple Votings are possible from different clients

### ISSUE THREAD

**Issue by blueamerican** [pixelink/typo3-simplepoll#21]
I want to disallow several votings from one ip:

`plugin.tx_simplepoll.settings.ipBlock = 1`
`plugin.tx_simplepoll.settings.allowMultipleVote =` 0

Newertheless i can vote from different browsers.
One Time from FF, one time from chrome.. etc..

**Comment by alexxB** [comment]
I won't dive deep into this but have you changed the garbage collector interval?
The default value is quite low with 10 seconds. 
`garbageCollectorInterval = 10`
That means after 10 seconds you are allowed to vote again.

**Comment by blueamerican** [comment]
ah ok.

**Comment by alexxB** [comment]
You are welcome... *rollEyes*
