### ISSUE TITLE
TemplateRoot,Layout, Partial paths are wrong

### ISSUE THREAD

**Issue by mario-naether** [pixelink/typo3-simplepoll#7]
Hi,

in your currently master/develop branch, there are the TypoScript Config for `templateRootPaths` , `partialRootPaths`, `layoutRootPaths` at a wrong position (not in "view").

Thake a look in this working changeset:
https://github.com/Emphis/typo3-simplepoll/commit/d9bd22fdadc25e2bdd5b15513fce973c0ef3e306

**Comment by alexxB** [comment]
Absolutely right. That snuck in, when I was including the changes made by Philipp Roski by Hand, since i had no pull request. Gonna fix that today.

Thanks a lot
