### ISSUE TITLE
v2.0 - Date-Fields dosn't work in TYPO3 7.6

### ISSUE THREAD

**Issue by mario-naether** [pixelink/typo3-simplepoll#9]
Hi,

you changed the Datefields TCA Config, `starttime`, `endtime`, `end_time` for TYPO3 8.7 and add a 
`'renderType' => 'inputDateTime'`
This dosn't work with 7.6.*
My output in the Backend Poll Edit view look like:

```
Endzeit
Unknown type: input
```

**Comment by briezler** [comment]
Hi Mario,

compatiblity for 7.6 is restored in master branch. We will release a TER update soon.

Thx for your input.

**Comment by alexxB** [comment]
Also rolled back a possible problem for localization which is v8 only
